import assert from 'node:assert/strict';
import { test, after } from 'node:test';
import { createServer } from 'vite';
import { Bone, BoxGeometry, Float32BufferAttribute, Group, Matrix4, MeshBasicMaterial, Skeleton, SkinnedMesh, Uint16BufferAttribute } from 'three';
const server = await createServer({ server: { middlewareMode: true, watch: null, ws: false }, appType: 'custom' });
after(() => server.close());
const { AssetLoader } = await server.ssrLoadModule('/src/assets/AssetLoader.ts');
const { HumanoidFleet } = await server.ssrLoadModule('/src/humanoids/HumanoidFleet.ts');
const { AssetRegistry } = await server.ssrLoadModule('/src/assets/AssetRegistry.ts');
const { AnimationSystem } = await server.ssrLoadModule('/src/animation/AnimationSystem.ts');
test('shared rigs stay pristine and clones measure consistently before their first render', async () => {
  const geometry = new BoxGeometry(1, 2, 1);
  const count = geometry.attributes.position.count;
  geometry.setAttribute('skinIndex', new Uint16BufferAttribute(new Uint16Array(count * 4), 4));
  const weights = new Float32Array(count * 4);
  for (let i = 0; i < count; i++) weights[i * 4] = 1;
  geometry.setAttribute('skinWeight', new Float32BufferAttribute(weights, 4));
  const source = new Group(), bone = new Bone();
  const mesh = new SkinnedMesh(geometry, new MeshBasicMaterial());
  mesh.scale.setScalar(0.01); source.add(mesh, bone);
  source.updateMatrixWorld(true);
  mesh.bind(new Skeleton([bone]), new Matrix4());
  source.updateMatrixWorld(true);
  const cached = { root: source, animations: [], instanceCount: 0 };
  const fleet = new HumanoidFleet(1);
  const loader = new AssetLoader(new Group(), new AssetRegistry([]), new AnimationSystem(), fleet);
  loader.getSource = async () => cached;
  const config = { type: 'humanoid', src: '/shared.glb', position: [5, 0, 3], rotation: [0, 0.4, 0], scale: [1, 1, 1] };
  const first = await loader.load({ ...config, id: 'one' });
  assert.equal(source.parent, null);
  assert.notEqual(first.model, source);
  first.root.scale.setScalar(3);
  first.root.updateMatrixWorld(true);
  const second = await loader.load({ ...config, id: 'two' });
  assert.ok(Math.abs(first.normalization.nativeHeight - 2) < 1e-6);
  assert.equal(first.normalization.nativeHeight, second.normalization.nativeHeight);
  const firstMesh = first.model.children.find(child => child.isSkinnedMesh);
  const secondMesh = second.model.children.find(child => child.isSkinnedMesh);
  assert.notEqual(firstMesh.skeleton, secondMesh.skeleton);
  assert.equal(firstMesh.geometry, secondMesh.geometry);
  assert.equal(firstMesh.material, secondMesh.material);
  loader.dispose();
});
