import { EQUIPMENT_STAGING } from './scene1DemoRoute';
import { AIRLOCK_PLACEMENT } from './airlockPlacement';
import { MOONTOLOGY_CONFIG } from '../config/moontologyConfig';
import type {
  LevelAssetConfig,
  SceneWorkGroupConfig,
  StaticSystemsConfig,
} from './types';

export const SCENE_1_STATIC_ASSETS = [
  {
    id: 'EXC-01',
    type: 'rover',
    src: '/models/rovers/lunar%20excavator.glb',
    role: 'Primary Regolith Excavator',
    ...EQUIPMENT_STAGING['EXC-01'],
    scale: [1, 1, 1],
    visible: true,
    sceneTags: ['scene-1', 'regolith-shift', 'excavation'],
    association: {
      entityId: 'EXC-01',
      assignedWorker: 'H01',
      assignedWorkers: ['H01'],
      taskId: 'RegolithExcavation-04',
      workGroupIds: ['RegolithWorkGroup'],
      relatedEntityIds: ['H01', 'Stop-H01'],
    },
    targetLengthMeters: MOONTOLOGY_CONFIG.physicalScale.excavatorLength,
    groundY: 0,
    castShadow: true,
    receiveShadow: true,
  },
  {
    id: 'EXC-02',
    type: 'equipment',
    src: '/models/static/excavator%20traditional.glb',
    role: 'Standby Regolith Excavator',
    ...EQUIPMENT_STAGING['EXC-02'],
    scale: [1, 1, 1],
    visible: true,
    sceneTags: ['scene-1', 'regolith-shift', 'excavation', 'standby'],
    association: {
      entityId: 'EXC-02',
      assignedWorker: 'H01',
      assignedWorkers: ['H01'],
      taskId: 'RegolithExcavation-04',
      workGroupIds: ['RegolithWorkGroup'],
      relatedEntityIds: ['H01', 'EXC-01', 'Stop-H01'],
    },
    targetLengthMeters: MOONTOLOGY_CONFIG.physicalScale.excavatorLength,
    groundY: 0,
    castShadow: true,
    receiveShadow: true,
  },
  {
    id: 'CABLE-ROVER-01',
    type: 'rover',
    src: '/models/static/cable.glb',
    role: 'Cable Deployment System',
    ...EQUIPMENT_STAGING['CABLE-ROVER-01'],
    scale: [1, 1, 1],
    visible: true,
    sceneTags: ['scene-1', 'regolith-shift', 'cable-deployment'],
    association: {
      entityId: 'CABLE-ROVER-01',
      assignedWorker: 'H02',
      assignedWorkers: ['H02'],
      taskId: 'CableDeployment-17',
      workGroupIds: ['CableWorkGroup'],
      relatedEntityIds: ['H02', 'PowerNode-B', 'CableRun-17'],
    },
    targetLengthMeters: MOONTOLOGY_CONFIG.physicalScale.cableRoverLength,
    groundY: 0,
    castShadow: true,
    receiveShadow: true,
  },
  {
    id: 'ROVER-01',
    type: 'rover',
    src: '/models/animated/rover-driving.glb',
    animation: 'Drive_InPlace',
    animationSpeed: 0,
    role: 'Surface Support Rover',
    ...EQUIPMENT_STAGING['ROVER-01'],
    scale: [1, 1, 1],
    visible: true,
    sceneTags: ['scene-1', 'regolith-shift', 'surface-maintenance'],
    association: {
      entityId: 'ROVER-01',
      assignedWorker: 'H03',
      assignedWorkers: ['H03'],
      taskId: 'WorkerRecovery-12',
      workGroupIds: ['SurfaceMaintenanceGroup'],
      relatedEntityIds: ['H03', 'Stop-H03'],
    },
    targetLengthMeters: MOONTOLOGY_CONFIG.physicalScale.utilityRoverLength,
    groundY: 0,
    castShadow: true,
    receiveShadow: true,
  },
  {
    id: 'LOGISTICS-ROVER-01',
    type: 'rover',
    src: '/models/animated/logistics-rover.glb',
    role: 'Logistics Equipment Staging Rover',
    ...EQUIPMENT_STAGING['LOGISTICS-ROVER-01'],
    scale: [1, 1, 1],
    visible: true,
    sceneTags: ['scene-1', 'regolith-shift', 'logistics'],
    association: {
      entityId: 'LOGISTICS-ROVER-01',
      assignedWorker: 'H04',
      assignedWorkers: ['H04'],
      taskId: 'InventoryAudit-06',
      workGroupIds: ['LogisticsGroup'],
      relatedEntityIds: ['H04', 'Stop-H04'],
    },
    targetLengthMeters:
      MOONTOLOGY_CONFIG.physicalScale.logisticsRoverLength,
    groundY: 0,
    castShadow: true,
    receiveShadow: true,
  },
  {
    id: 'Airlock-2A',
    type: 'airlock',
    src: null,
    procedural: 'facade-airlock-anchor',
    role: 'Habitat Pressure Door',
    ...AIRLOCK_PLACEMENT,
    visible: true,
    sceneTags: ['scene-1', 'airlock', 'habitat-access'],
    association: {
      entityId: 'Airlock-2A',
      workGroupIds: ['AirlockGroup'],
      relatedEntityIds: ['Habitat-2'],
    },
  },
  {
    id: 'Airlock-2A-LeakOrigin',
    type: 'infrastructure',
    src: null,
    procedural: 'airlock-leak-origin',
    parentAssetId: 'Airlock-2A',
    role: 'Lower Seal Leak Origin',
    position: [0, -1.42, 0.09],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    visible: true,
    sceneTags: ['scene-1', 'airlock', 'debug-anchor'],
    association: {
      entityId: 'Airlock-2A-LeakOrigin',
      workGroupIds: ['AirlockGroup'],
      relatedEntityIds: ['Airlock-2A'],
    },
  },
  {
    id: 'PowerNode-B',
    type: 'infrastructure',
    src: null,
    procedural: 'cable-endpoint',
    role: 'Cable Run Destination Connector',
    ...EQUIPMENT_STAGING['PowerNode-B'],
    scale: [1, 1, 1],
    visible: true,
    sceneTags: ['scene-1', 'cable-deployment', 'power'],
    association: {
      entityId: 'PowerNode-B',
      assignedWorkers: ['H02'],
      taskId: 'CableDeployment-17',
      workGroupIds: ['CableWorkGroup'],
      relatedEntityIds: ['CABLE-ROVER-01', 'CableRun-17'],
    },
  },
] as const satisfies readonly LevelAssetConfig[];

export const SCENE_1_WORK_GROUPS = [
  {
    id: 'RegolithWorkGroup',
    role: 'Regolith Excavation',
    memberEntityIds: ['H01', 'EXC-01', 'EXC-02', 'Stop-H01'],
    sceneTags: ['scene-1', 'regolith-shift', 'excavation'],
  },
  {
    id: 'CableWorkGroup',
    role: 'Power Inspection and Cable Deployment',
    memberEntityIds: [
      'H02',
      'CABLE-ROVER-01',
      'CableRun-17',
      'PowerNode-B',
    ],
    sceneTags: ['scene-1', 'regolith-shift', 'cable-deployment'],
  },
  {
    id: 'SurfaceMaintenanceGroup',
    role: 'Surface Support and Worker Recovery',
    memberEntityIds: ['H03', 'ROVER-01', 'Stop-H03'],
    sceneTags: ['scene-1', 'regolith-shift', 'surface-maintenance'],
  },
  {
    id: 'LogisticsGroup',
    role: 'Logistics Inventory and Equipment Staging',
    memberEntityIds: [
      'H04',
      'LOGISTICS-ROVER-01',
      'Stop-H04',
    ],
    sceneTags: ['scene-1', 'regolith-shift', 'logistics'],
  },
  {
    id: 'AirlockGroup',
    role: 'Habitat Airlock Interaction',
    memberEntityIds: [
      'Airlock-2A',
      'Airlock-2A-LeakOrigin',
      'Habitat-2',
    ],
    sceneTags: ['scene-1', 'airlock', 'habitat-access'],
    interactionPoints: [
      {
        id: 'Airlock-2A-PurgePoint',
        role: 'Go2 Handshake / Purge Trigger',
        position: [-0.9, -0.72, -16.6],
        sceneTags: ['airlock', 'purge', 'go2'],
      },
      {
        id: 'Airlock-2A-EmergencyPoint',
        role: 'Go2 Pounce / Emergency Hatch Trigger',
        position: [-0.3, -0.72, -16.6],
        sceneTags: ['airlock', 'emergency', 'go2'],
      },
    ],
  },
] as const satisfies readonly SceneWorkGroupConfig[];

export const SCENE_1_STATIC_SYSTEMS = {
  cable: {
    enabled: true,
    roverAssetId: 'CABLE-ROVER-01',
    endpointAssetId: 'PowerNode-B',
    cableEntityId: 'CableRun-17',
    taskId: 'CableDeployment-17',
    outletPosition: [0, 0.42, 0.95],
    initialState: 'PARTIAL',
    partialRatio: 0.62,
  },
  airlock: {
    assetId: 'Airlock-2A',
    leakOriginAssetId: 'Airlock-2A-LeakOrigin',
    closedPosition: [0, 0, 0],
    openPosition: [0, 2.9, 0],
    moveDurationSeconds: 2.2,
    purgeDurationSeconds: 1.8,
    emergencyFaultHoldSeconds: 0.45,
    emergencyOpenHoldSeconds: 0.75,
    leakParticleCount: 48,
  },
} as const satisfies StaticSystemsConfig;
